[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-bootstrap-stt",
    "allow-transcribe-file",
    "allow-stt-health",
    "allow-initialize-recorder-runtime",
    "allow-start-recording",
    "allow-stop-recording",
    "allow-set-hotkey-bindings",
    "allow-capture-hotkey",
    "allow-get-runtime-state",
    "allow-set-output-destination",
    "allow-get-output-destination",
    "allow-set-overlay-mode",
    "allow-get-overlay-mode"
]
